const jwtDecode = require('jwt-decode');

const dec = jwtDecode("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3RuYW1lIjoiYW5pa2V0IiwibGFzdG5hbWUiOiJtb3JlIiwiZW1haWwiOiJhbmlrZXRAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJwYXNzd29yZEtleSI6ImRiMGQ2MDRhMDBkMjZhZjYwMDZkM2MyYzA0MDNkZGFlNjZmY2I4Y2JkNzFkNjAzNjMzMzNmMGUwNzQxYzQzOWUiLCJpYXQiOjE2MzcyNjE3NTEsImV4cCI6MTYzNzM0ODE1MX0.qZUkDh6I1A4rzQpVNEZnxyFRSW-nEf34L3AhHYUmbf0");

console.log(dec);